#!/usr/bin/python
import sys

try:
    from flake8.main import git

    if __name__ == '__main__':
        sys.exit(
            git.hook(
                strict=True,
                lazy=git.config_for('lazy'),
            )
        )
except ImportError:
    print("Can't run flake8 because it isn't available.")
